- name: redis subnet group
  elasticache_subnet_group:
    description: redis subnet group
    state: present
    name: redisgroup
    region: "{{ region }}"
    subnets:
      - "{{ subnet1.subnet.id }}"
- name: redis
  elasticache:
    name: "kafka-storm"
    state: present
    engine: redis
    cache_engine_version: 5.0.3
    node_type: cache.t2.micro
    num_nodes: 1
    security_group_ids: "{{ security_group.group_id }}"
    cache_port: 6379
    cache_subnet_group: "{{'redisgroup'}}"
  register: redis
- name: debugging
  debug:
    msg: "{{ redis.elasticache.data.CacheNodes[0].Endpoint.Address }}"
- name: open ssh tunnel
  command: ssh -i /home/tigstep/csaa_ec2_key.pem -f -N -L6379:{{ redis.elasticache.data.CacheNodes[0].Endpoint.Address }}:6379 ec2-user@"{{ groups['ec2_group'][0] }}" &
- name: wait 10 seconds
  pause:
    seconds: 10
- name: populate redis
  command: chdir=/mnt/c/Users/Tigran/IdeaProjects/kafka_storm_pipeline/redisInserter/target java -jar RedisInserter.jar