- name: kafkastorm security group
  ec2_group:
    name: kafkastorm
    description: kafkastorm security group
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 2181
        to_port: 2181
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 2888
        to_port: 2888
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3888
        to_port: 3888
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9092
        to_port: 9092
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 6627
        to_port: 6627
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 6700
        to_port: 6700
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 6701
        to_port: 6701
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 6702
        to_port: 6702
        cidr_ip: 0.0.0.0/0
  register: security_group