- name: Pull the storm image
  docker_image:
    name: storm
- name: Start the storm nimbus
  shell: docker run -d --restart=always -p 6700:6700 -p 6701:6701 -it -v /etc/storm.yaml:/conf/storm.yaml storm storm supervisor