- name: kafkastorm VPC
  ec2_vpc_net:
          name: "{{vpc_name}}"
          region: "{{region}}"
          state: present
          cidr_block: "{{cidr_block}}"
          resource_tags: { "Name":"{{tag_name}}" }
  register: vpc