- name: kafkastorm subnet
  ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ cidr_block }}"
        resource_tags:
          Name: "{{ tag_name }}"
  register: subnet