- name: Upgrade all packages
  yum:
      name: '*'
      state: latest
- name: Check if Docker is installed
  command: systemctl status docker
  register: docker_check
  ignore_errors: yes
#- name: Download the Docker installer
#  get_url:
#      url: https://get.docker.com/
#      dest: /root/install_docker.sh
#      mode: 0700
#  when: docker_check.stderr.find('service could not be found') != -1
#- name: Install Docker
#  shell: yum install docker
#  shell: /root/install_docker.sh
#  when: docker_check.stderr.find('service could not be found') != -1
- name: Install docker
  yum:
    name: docker
    state: latest
- name: Remove the Docker installer file.
  file:
    state: absent
    path: /root/install_docker.sh
- name: Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no
- name: Start the Docker daemon
  systemd:
    name: docker
    state: started
    masked: no
- name: Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes
- name: Download and install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
- name: install pip
  yum:
    name: python-pip
    state: latest
- name: install pip docker
  pip:
    name: docker
- name: Log into DockerHub
  docker_login:
    username: ""
    password: ""
- name: Pull the zookeeper image
  docker_image:
    name: jeygeethan/zookeeper-cluster
- name: Start the container
  shell: docker run -d --restart=always -p 2181:2181 -p 2888:2888 -p 3888:3888 -v /var/lib/zookeeper:/var/lib/zookeeper -v /var/log/zookeeper:/var/log/zookeeper jeygeethan/zookeeper-cluster {{ hostvars[groups['ec2_group'][0]]['inventory_hostname'] }},{{ hostvars[groups['ec2_group'][1]]['inventory_hostname'] }} {{ groups['ec2_group'].index(inventory_hostname) + 1 }}