---
- hosts: localhost
  vars_files:
    - ./roles/vpc/vars/main.yml
  environment:
    AWS_PROFILE: "terraform_user"
  roles:
    - ../roles/vpc
    - ../roles/subnet
    - ../roles/security_group
    - ../roles/ec2